charts/flagsmith/templates/_helpers.tpl, charts/flagsmith/templates/deployment-api.yaml
I think this had previously assumed that the release name would always be `flagsmith`. This fixes to use the correct value.
=> Fix for alternate helm release name

.github/workflows/lint-test.yaml
While there's only one chart, this is still useful as it means changes to things like the top-level README don't require the full KinD testing to run.
=> Only lint and test changed charts

.github/workflows/release.yaml
Publish charts using https://github.com/helm/chart-releaser-action, hosted at https://flagsmith.github.io/flagsmith-charts/ using GitHub pages.
=> Publish chart using gh-pages

charts/flagsmith/Chart.yaml
Artifacthub was unhappy with a .ico. Docs at https://helm.sh/docs/topics/charts/ say it should be happy with a .png.
This might not be the right icon forever, but should do for the time being.
=> Fix chart icon to be a .png not .ico

charts/flagsmith/Chart.yaml, charts/flagsmith/README.md, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/values.yaml
Use known good tags, defaulting to version set in `Chart.yaml`'s `appVersion`.
=> Specify image tags, via appVersion

charts/flagsmith/Chart.yaml, charts/flagsmith/README.md, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/values.yaml
Makes use of `wait-for-it.sh` to check the DB is accessible before starting the API pods. This means they don't begin crashing, but rather just quietly wait.
=> Wait for DB to be ready before starting api containers

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/NOTES.txt
Prints a message to the console post-install, that looks a bit like:
```
NOTES:
See documentation at https://artifacthub.io/packages/helm/flagsmith/flagsmith/0.1.4
for more configuration options.
See documentation at https://artifacthub.io/packages/helm/flagsmith/flagsmith/0.1.4#ingress-configuration
for information about how to gain web access to the application.
```
Conditionally handles ingress for frontend and/or api being disabled, alerting the user to the need to gain web access.
=> Chart NOTES.txt

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/_helpers.tpl, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/ingress-api.yaml, charts/flagsmith/templates/ingress-frontend.yaml, charts/flagsmith/templates/routes-api.yaml, charts/flagsmith/templates/routes-frontend.yaml, charts/flagsmith/templates/secrets-api.yaml, charts/flagsmith/templates/service-api.yaml, charts/flagsmith/templates/service-frontend.yaml
See https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
Note: this is a breaking change, as updating the selector labels on the deployment will upset the running pods. Given we're at `0.1.x`, I think this is OK, but have bumped to `0.2.0`.
=> Standard kubernetes labels

charts/flagsmith/Chart.yaml, charts/flagsmith/README.md, charts/flagsmith/templates/_helpers.tpl, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/persistance-volume-claim-influxdb.yaml, charts/flagsmith/templates/secrets-influxdb-external.yaml, charts/flagsmith/templates/secrets-influxdb.yaml, charts/flagsmith/templates/service-influxdb.yaml, charts/flagsmith/templates/statefulset-influxdb.yaml, charts/flagsmith/values.yaml
Set env-vars in the API deployment to connect to InfluxDB.
Also allows InfluxDB to be turned off.
Also allows retrieving the InfluxDB token from an existing k8s secret.
Some implementation notes:
- Also sets annotations on the API pods so they get cycled when the InfluxDB config they reference changes
- Though this doesn't work for an external k8s secret, pods would need to be manually cycled in that case
- Have kept the config for the external InfluxDB separated from the internal. I'm a bit torn, but I don't think it makes heaps of difference really.
=> InfluxDB options and environment variables

tools/lint.sh
Using docker to run the local-linting means that any files it writes are owned by root. In particular, any sub-charts directories. This tidies those generated directories away.
=> Lint utility: tidy generated charts directories

charts/flagsmith/Chart.yaml, charts/flagsmith/README.md, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/values.yaml
Don't use `values` to set env-vars that we know need setting. And use a dictionary to handle env-vars to allow for easier overwriting if using multiple values files.
=> Neater environment handling for overwrites

tools/lint.sh
Cleanup any sub-charts and any sub-tmpcharts directories. And do this before linting, and after linting, even if linting fails.
=> Lint utility: even more thorough tidying

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/_helpers.tpl, charts/flagsmith/templates/deployment-api.yaml
Fix so that the chart-managed InfluxDB uses the correct hostname in the URL.
=> Fix InfluxDB env-vars

charts/flagsmith/Chart.yaml, charts/flagsmith/README.md, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/secrets-api.yaml, charts/flagsmith/values.yaml
- Always set `DATABASE_URL`, don't duplicate config to other DB-based env vars
- Allow setting config for an external database (be it PostgreSQL or otherwise)
- Allow referencing an existing secret that contains the database URL
=> More PostgreSQL and database options

charts/flagsmith/Chart.yaml, charts/flagsmith/README.md, charts/flagsmith/templates/NOTES.txt, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/values.yaml
Enable the frontend proxy by default and document.
And this allows for a really simple quick-start, so have documented that, and added steps to `NOTES.txt` that get shown to the user post-install so they know how to gain access.
=> Frontend proxy on by default

charts/flagsmith/Chart.yaml, charts/flagsmith/README.md, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/values.yaml
I have made no effort to come up with the answers that will always be correct, because they depend on the cluster, but I think this is a sensible start.
As it stands, this doesn't actually apply any security context by default. Though I would like to be able to enable `runAsNonRoot`, because I think that is the one we are mostly likely to hit, and I suspect application changes to accommodate will be quite easy.
=> Config for pod security context

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml
Change proposal is to not wait for external database in flagsmith-api
=> Don't wait for local Postgres service if configured to connect to external database

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml
there is minimum version not working on `main` branch
```yaml
api:
nodeSelector:
kubernetes.io/arch: amd64
```
error:
```
Error: YAML parse error on flagsmith/templates/deployment-api.yaml: error converting YAML to JSON: yaml: line 31: mapping values are not allowed in this context
```
this PR contains working version
=> fix affinity, nodeSelector and tolerations

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/ingress-api.yaml, charts/flagsmith/templates/ingress-frontend.yaml
`semverCompare ">=1.18.0" .Capabilities.KubeVersion.GitVersion` will work only for simple versions `v1.18.x` but not with extended versions `v1.15.12-eks-9fd540` (AWS EKS) replacing `>=1.18.0` with `>=1.18-0` fixies it.
also stable version of ingress is available from `1.19+` not `1.18+`. see https://v1-19.docs.kubernetes.io/docs/setup/release/notes/
=> fix kubernetes version detection in ingress

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/service-frontend.yaml, charts/flagsmith/values.yaml
This is my attempt at a minimally disruptive way of supporting the all-in-one Docker image, https://hub.docker.com/r/flagsmith/flagsmith/.
Documented https://github.com/Flagsmith/flagsmith-docs/pull/44
Some notes:
- This just reuses the api deployment, but points the frontend service at it
- So the service and ingress for the frontend remain (unless explicitly switched off)
- To use this, need to explicitly set the following:
- `api.image.repository: flagsmith/flagsmith`
- `api.separateApiAndFrontend: false`
- `api.image.tag: 2.14` (or some other tag that exists in https://hub.docker.com/r/flagsmith/flagsmith/tags)
By default (ie, if `api.separateApiAndFrontend` is left at its default value of `true`) my changes here are a no-op, so this change will not break any existing installations. …
=> Option to use the all-in-one Docker image

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/service-api.yaml, charts/flagsmith/templates/service-frontend.yaml, charts/flagsmith/values.yaml
Thanks for submitted a PR! Please check the boxes below:
This PR adds the ability to template annotations into the `flagsmith-api` and `flagsmith-frontend` Services. This was done so users could add their own annotations for any use case.
Closes #65
- Ran `tools/lint.sh` and ensured there were no errors
- Added a default `test: foo` annotation to both Services and ran a dry run to ensure they were applied as expected (which they were):
```shell
helm upgrade flagsmith ./charts/flagsmith --dry-run --debug --install --values ./charts/flagsmith/values.yaml
```
=> Add ability to template annotations into flagsmith-api and flagsmith-frontend Services

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/ingress-frontend.yaml, charts/flagsmith/templates/service-frontend.yaml, charts/flagsmith/values.yaml
Fixes #69 by honouring the `frontend.enabled` flag.
Deployed to minikube. Set `frontend.enabled` to `false` and saw that the deployment, service and ingress for the frontend were removed.
=> Fix frontend.enabled switch

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/ingress-api.yaml, charts/flagsmith/templates/ingress-frontend.yaml, charts/flagsmith/values.yaml
Allow setting `ingressClassName` on the created ingress objects. Fixes #72.
Having looked at the following, have concluded this is set in the same place regardless of the API version for the ingress object:
```
$ kubectl explain ingress.spec.ingressClassName --api-version networking.k8s.io/v1
$ kubectl explain ingress.spec.ingressClassName --api-version networking.k8s.io/v1beta1
$ kubectl explain ingress.spec.ingressClassName --api-version extensions/v1beta1
```
Docs here https://github.com/Flagsmith/flagsmith-docs/pull/96
Deployed to minikube and ran `helm diff` after setting a value for `ingress.api.ingressClassName` and `ingress.frontend.ingressClassName`.
=> Issue 72: ingressClassName

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/_api_environment.yaml
Adds the USE_X_FORWARDED_HOST environment variable if using the apiProxy. 
This ensures that the API publishes obtains correct URL when using `request.build_absolute_uri`, for example when generating the entity_id and ACS URL in the SAML handshake. 
Deployed the helm chart locally using minikube and ran `kubectl set env deployment/flagsmith-api --list` to confirm that the environment variable is set correctly. 
Fixes #80
=> Add USE_X_FORWARDED_HOST setting

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/NOTES.txt, charts/flagsmith/templates/_api_environment.yaml, charts/flagsmith/templates/secrets-api.yaml, charts/flagsmith/values.yaml
Allow the `DJANGO_SECRET_KEY` environment variable to be set for the API from the `api.secretKey` value in helm.
By default, this is set to nothing and falls back to existing behaviour. However, it prints a slight obnoxious message after doing deploying with helm to warn about it.
Helm really doesn't handle "generate a random string once and remember it" well at all, see https://helm.sh/docs/howto/charts_tips_and_tricks/#be-careful-with-generating-random-values. There are some workarounds, like https://stackoverflow.com/questions/56170052/how-not-to-overwrite-randomly-generated-secrets-in-helm-templates but I think by far the least surprising is what I have done here.
Set `api.secretKey: abc123`, deployed, then, in an api pod, ran: …
=> Issue 79: set DJANGO_SECRET_KEY environment variable

charts/flagsmith/Chart.yaml, charts/flagsmith/ci/e2e-test-values.yaml, charts/flagsmith/templates/_api_environment.yaml, charts/flagsmith/templates/_helpers.tpl, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/tests/test-e2e-monster.yaml, charts/flagsmith/values.yaml, ct.yaml
Fixes #40.
This is my "monster" for running the E2E tests. I retrieves the git sha from the API container, then using a plain Ubuntu image, installs dependencies, clones the code from Github, then runs the tests.
Waited for CI.
----
This is now passing CI, but with some caveats:
- The yucky work-out-the-git-sha-and-clone-from-github-etc-etc, which could be remedied by #86
- I've had to do some hacking to make it use firefox instead of chrome for it to run in Github actions. I'm not really sure why this made a difference. Debug logs from the test runner might help, but I'm mostly just confused by this. It ran with chrome locally, but not in Github. See #87
- It would be nice if the e2e-testing image had both Firefox and Chrome …
=> Issue 40: e2e tests

charts/flagsmith/values.yaml
Correctly add the health path to the api section in values.yaml instead of the pgbouncer section.
Reliant on automated tests
=> Move health path from pgbouncer to api

.github/workflows/release.yaml, ct.yaml
Have made #105 to find a way of doing this better, maybe.
For now, just setting the repo in the place where it is currently missing is probably best, as it means the merged chart can be released.
=> Fix release action

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/_helpers.tpl, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/deployment-pgbouncer.yaml
Fixes #113.
If `replicacount` is null, don't set replicas on a deployment.
Deployed to minikube with `replicacount` set to `null` and then 0 and saw that the right thing happened.
=> Do not set replicas if set to null

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/deployment-pgbouncer.yaml, charts/flagsmith/values.yaml
Fixes #114.
Allow setting the strategy on the deployments. See https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
I have decided that this is a "change" but #115 is a "fix", mostly so the chart version numbers are a bit less faffy for me, but only if this PR is merged after #115. Happy to adjust.
Deployed to minikube, tested that setting values for this do indeed get set on the deployments.
=> Allow setting strategy on deployments

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/NOTES.txt, charts/flagsmith/templates/_api_environment.yaml, charts/flagsmith/templates/secrets-api.yaml
By default, set a randomly generated value for the secret key. This changes the existing behaviour, where no value is set, so each container in each API pod will generate itself a secret key at startup, so with multiple replicas, each will end up with a different secret key, which will confuse some things. A consistent value across all running pods is better.
In practice, deployments ought to have set `api.secretKey`, per the message generated from `NOTES.txt`.
So while this is not ideal (helm makes it fiddly to do better), I believe it is a strict improvement. And the "right answer" remains "set `api.secretKey`".
Deployment to minikube, saw that a value was generated, but I still got a warning:
``` …
```
=> Generate secret key if not set

charts/flagsmith/Chart.yaml, charts/flagsmith/ci/influxdb-test-values.yaml, charts/flagsmith/templates/_influxdb_setup.txt, charts/flagsmith/templates/configmap-influxdb-setup.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/values.yaml
Added script to setup InfluxDB per https://docs.flagsmith.com/deployment/overview#influxdb
This is controlled by the `api.influxdbSetup.enabled` switch. If this is set to `true`, then on startup, the application will check that buckets and tasks with the expected names exist, and create them if they do not. It will not update existing buckets or tasks with those names.
Note the switch is off by default. This is because if users have created tasks with different names, then this code will effectively duplicate them, which I think would be bad. (There is probably a backwards-incompatible chart change coming up in the medium term to change defaults like this, but will need documentation to tell users how to retain existing behaviour.) …
=> Automated InfluxDB setup steps

charts/flagsmith/templates/deployment-task-processor.yaml, charts/flagsmith/values.yaml
Separates the task processor image configuration from the API image configuration.
- Verified all combinations of default values using `helm template` command. 
- Verified that running the task processor and API containers using different images works correctly
=> Separate task processor image from API

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/_api_environment.yaml, charts/flagsmith/values.yaml
release branch
Allows setting the `DJANGO_SECRET_KEY` environment variable from an existing kubernetes secret.
After my changes I ran:
`helm template flagsmith-test .` from the `charts/flagsmith` directory and verified that the default behavior still persisted
Then I ran:
`helm template flagsmith-test . --set api.secretKeyFromExistingSecret.enabled=true,api.secretKeyFromExistingSecret.name=asdf,api.secretKeyFromExistingSecret.key=YEP` and verified that the secret used the provided name and key.
=> Django secret key existing secret

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/ingress-api.yaml, charts/flagsmith/templates/ingress-frontend.yaml, charts/flagsmith/values.yaml
release branch
This PR removes the ability to set custom paths for ingresses (issue #138). 
Deployed it on a local cluster with ingresses enabled.
=> fix!: remove ability to specify ingress paths (#138)

charts/flagsmith/Chart.yaml
Bump the appVersion in the chart templates.
2.57.0 is currently running in SaaS production and well tested.
=> Bump appVersion 2.57.0

.gitignore, charts/flagsmith/Chart.yaml, charts/flagsmith/templates/ingress-api.yaml, charts/flagsmith/values.yaml
PR #139 correctly fixed a pathing issue for the front-end ingress, but also made the same changes to the API server ingress in order to maintain consistency between the two. However, changing the ingress in the latter case was unnecessary and broke deployments that used specialized paths for the API server (e.g. using rewrites). This PR reverts the changes for the API server ingress and leaves the changes to the front-end ingress untouched.
release branch
- Reverted changes to the API server ingress
_Please describe._
=> fix: revert pathing changes to API Ingress

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/values.yaml
Fixes #111.
release branch
Add option to use the `waitfordb` command from the application Docker image, rather than pulling in a separate image for this purpose.
```shell
$ helm -n flagsmith get values flagsmith-test -o json | jq .api.dbWaiter.useExternalImage
null
$ kubectl -n flagsmith get deployments.apps -o json | jq -r '[(.items[] | (.spec.template.spec.initContainers // []) | .[].image)] | unique | .[]' 
flagsmith/flagsmith-api:2.42.1
willwill/wait-for-it:latest
...
$ helm -n flagsmith get values flagsmith-test -o json | jq .api.dbWaiter.useExternalImage
false
$ kubectl -n flagsmith get deployments.apps -o json | jq -r '[(.items[] | (.spec.template.spec.initContainers // []) | .[].image)] | unique | .[]' 
flagsmith/flagsmith-api:2.42.1
```
Some considerations:
- default behaviour …
=> Issue 111: option to remove use of waitforit image

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/_api_environment.yaml, charts/flagsmith/values.yaml
release branch
Allows using the credentials of influxDB(not external) from from an existing k8s secret.
1. I have checked that it is possible in dependent chart: https://github.com/influxdata/helm-charts/blob/3c10c43fa0b5a87bf03a70db59ce700665da0997/charts/influxdb2/values.yaml#L109 
2. I ran:
`helm template flagsmith-test .` from the charts/flagsmith directory and verified that the default behavior still persist
3. Finally, I ran:
`helm template flagsmith-test . --set influxdb2.adminUser.existingSecret=influxdb-secret` and verified that in the API deployment uses existing secret.
=> fix: allow using influxDB credentials from existing secret

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/deployment-pgbouncer.yaml, charts/flagsmith/templates/deployment-task-processor.yaml, charts/flagsmith/values.yaml
release branch
Resolves #149
This adds support for injection of abritrary init containers and containers to all the deployments covered by this helm chart. The value names used are `extraInitContainers` and `extraContainers` - various other helm charts use these names, so I've looked to use them too. Note that 3 of the deployments don't actually have init containers as standard, but IMO it seems sensible to use "extra" for consistency, and also in case there are requirements for init containers in the future.
- I ran `helm template .` and inspected the output with none of the new values defined
- I ran `helm template .` and inspected the output with the new values defined, but empty arrays
- I ran `helm template .` and inspected …
=> Support injection of extra init containers and containers

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/_task_processor_environment.yaml, charts/flagsmith/templates/deployment-task-processor.yaml
release branch
Adds the RUN_BY_PROCESSOR environment variable to the task processor. 
This is a temporary fix until we can complete [this issue](https://github.com/Flagsmith/flagsmith/issues/3317) in the main repository and replace the run command here with a call to the run-docker script instead. 
Ran the chart locally and confirmed that the `RUN_BY_PROCESSOR` variable is set in the task processor pods and all pods come up healthy.
=> fix(task-processor): add run by processor

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/_task_processor_environment.yaml, charts/flagsmith/templates/deployment-task-processor.yaml
release branch
Uses the run-docker.sh script to run the task processor instead of manually calling `python manage.py runprocessor`. 
Ran the chart locally and tested changing each of the initialisation parameterts.
=> chore: Use run-docker script for task processor

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/_helpers.tpl, charts/flagsmith/templates/configmap-influxdb-setup.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/deployment-pgbouncer.yaml, charts/flagsmith/templates/deployment-task-processor.yaml, charts/flagsmith/templates/ingress-api.yaml, charts/flagsmith/templates/ingress-frontend.yaml, charts/flagsmith/templates/routes-api.yaml, charts/flagsmith/templates/routes-frontend.yaml, charts/flagsmith/templates/secrets-api.yaml, charts/flagsmith/templates/secrets-influxdb-external.yaml, charts/flagsmith/templates/secrets-pgbouncer.yaml, charts/flagsmith/templates/service-api.yaml, charts/flagsmith/templates/service-frontend.yaml, charts/flagsmith/templates/service-pgbouncer.yaml, charts/flagsmith/templates/tests/test-api-http-health.yaml, charts/flagsmith/templates/tests/test-e2e.yaml, charts/flagsmith/templates/tests/test-frontend-http.yaml, charts/flagsmith/values.yaml
release branch
* Adding `commonLabels` and `commonAnnotations` field to the values file
* Updating `flagsmith.labels` to use `commonLabels` if provided
* Adding `flagsmith.annotations` to use `commonannotations` if provided
* Adding annotations to places where they were missed
* Update existing annotations to add `commonAnnotations` as well
* Fix wrong annotations used in `service-fronend.yaml` file
I ran `helm install` with different parameters to verify that new labels and annotations are added only if needed.
=> Issue 159: Add common.label and common.annotations Helm parameters

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/jobs-migrate-db.yaml, charts/flagsmith/values.yaml
release branch
This PR does the following:
- Removes the wait-for-db init container as Flagsmith's entrypoint integrates this functionality.
- Adds an ability to remove the `migrate-db` init container.
- Adds an ability to deploy a `migrate-db` Kubernetes job, and customise it with extra containers and volumes.
This, along with #184, helps the chart users to add containers responsible for database connectivity, such as Google's `cloud-sql-proxy`. 
This code now works as part of one of our enterprise on-premise deployments.
=> feat: Migrate job, waiter deprecation, togglable init container

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/deployment-pgbouncer.yaml, charts/flagsmith/templates/deployment-task-processor.yaml, charts/flagsmith/values.yaml
release branch
This PR introduces a new `extraVolumes` attribute that can be provided to containers.
This is analogous with https://github.com/Flagsmith/flagsmith-charts/pull/150.
This, along with #188, helps the chart users to add containers responsible for database connectivity, such as Google's `cloud-sql-proxy`. 
CI tests cover the change.
Additionally, this is tested for one of the on-premise customers' deployment.
=> feat: Ability to provide extra volumes to containers

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/deployment-pgbouncer.yaml, charts/flagsmith/templates/deployment-task-processor.yaml, charts/flagsmith/templates/jobs-migrate-db.yaml
release branch
1. `migrate-db` job is now created with a unique suffix. This helps with the fact that k8s jobs are immutable and can not be updated in-place.
2. `shareProcessNamespace` container spec attribute is exposed to enable usage of tools like remote debuggers and profilers defined as additional pod containers.
Tested with one of the private cloud customers' cluster.
=> release: v0.30.0

charts/flagsmith/Chart.lock, charts/flagsmith/Chart.yaml, charts/flagsmith/README.md, charts/flagsmith/templates/_helpers.tpl, charts/flagsmith/values.yaml, ct.yaml
Fixes #121.
Update the bundled Postgres chart from chart version 8 in the old "stable" repos to chart version 12 in bitnami's repo.
**No effort has been made to preserve data. All of the k8s resources will get replaced. Per the warning at https://docs.flagsmith.com/deployment/kubernetes#provided-database-configuration, recommend storing data in an external database**
I reviewed the documentation at https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/ and determined that it would be silly to try to preserve data.
Further, have renamed to `dev-postgres` to make it very clear what this is for. There will be some documentation to update to accommodate this, but helm does handle our main use case: we …
=> Issue 121: update Postgres chart and identify as "dev"

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/jobs-migrate-db.yaml
release branch
_Please describe._
_Please describe._
=> fix: Lowercase names for migrate jobs

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/_task_processor_environment.yaml, charts/flagsmith/templates/deployment-task-processor.yaml
release branch
Fix bug introduced in thhis pr https://github.com/Flagsmith/flagsmith-charts/pull/187 
The environment variables added for the task processor should go inside the container that runs the task processor rather in the deployment template spec.
The task processor was already including the api environment so it was not necessary to add merge both `extraEnv`
Also the `extraEnv` keys and values were added as yaml (`key: value`), instead of the expected object with the `name` and `value` keys.
I test it manually. With a values
```
api:
extraEnv:
ALLOW_REGISTRATION_WITHOUT_INVITE: false
taskProcessor:
enabled: true
extraEnv:
foo: bar
```
The expected result in the api deployment, inside the `flagsmith-task-processor` …
=> fix(task-processor): the extraEnv where added in the wrong place

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/NOTES.txt, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/values.yaml
release branch
Closes https://github.com/Flagsmith/flagsmith-charts/issues/96.
This adds a documented way to pre-create default user/organisation/project.
Deployed to a local K8S cluster.
=> feat: Add default user/organisation/project bootstrapping

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/deployment-pgbouncer.yaml, charts/flagsmith/templates/deployment-task-processor.yaml
release branch
This allows to set a specific service account for every deployed pod.
Added the new key to values.yaml and observed the resulting k8s deployments.
=> feat: Ability to specify `serviceAccountName`

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/deployment-pgbouncer.yaml, charts/flagsmith/templates/deployment-task-processor.yaml
release branch
This fixes incorrect behaviour when Helm used `api`'s `serviceAccountName` for other deployments.
Deployed to local k8s.
=> fix: Incorrect `serviceAccountName` values

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/jobs-migrate-db.yaml
release branch
This adds the following:
- Exposes the `migrate-and-serve` entrypoint for those who wish to migrate in the entrypoint without resorting to a job or an init container.
- Exposes the `serviceAccoutName` spec for the migration job.
Observed the templated values locally.
=> feat: `serviceAccountName` for migrate job, expose `migrate-and-serve` entrypoint

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/extra-objects.yaml, charts/flagsmith/values.yaml
release branch
I'd like to be able to deploy other resources not included in the chart; Gateway HTTPRoutes, CloudnativePG Clusters etc.
I've added the same technique ArgoCD uses for this:
[ArgoCD](https://github.com/argoproj/argo-helm/blob/8b02b6d9b828902ba0d9ae1e6ddb4f060a5975ca/charts/argo-cd/values.yaml#L564-L591) - https://github.com/argoproj/argo-helm/blob/8b02b6d9b828902ba0d9ae1e6ddb4f060a5975ca/charts/argo-cd/templates/extra-manifests.yaml
Figured it was better than asking for every option under the sun for you to implement so I could use GatewayAPI HTTP Routes with Istio instead of Ingress objects.
Added an empty configMap to the helm values and deployed it and it was included in the helm release.
=> feat: add extraObjects

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml
release branch
This fixes wrong indentation when injecting environment for the `bootstrap` job with custom values.
Rendered the charts with custom bootstrap values present and made sure the rendering wasn't broken.
=> fix: Wrong indentation for the bootstrap job environment

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml
release branch
This _actually_ enables bootstrapping. 
Deployed to local k8s cluster without any custom environment variables.
=> fix: Set  `ALLOW_ADMIN_INITIATION_VIA_CLI` when `bootstrap.enabled` is `true`

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/deployment-task-processor.yaml, charts/flagsmith/values.yaml
release branch
Closes #291.
This allows to add arbitrary keys to both of the deployment's specs.
Added corresponding keys to `values.yaml` and observed the resulting template.
=> feat: Allow including extra `spec` keys for deployments

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/ingress-sse.yaml, charts/flagsmith/values.yaml
release branch
`ingress.sse` currently does nothing. This change adds a missing file to actually handle SSE ingress.
Manually using this values file:
<details>
```yaml
common:
labels: {}
annotations: {}
api:
image:
repository: flagsmith/flagsmith-private-cloud
tag: latest
imagePullPolicy: IfNotPresent
imagePullSecrets: []
#
separateApiAndFrontend: true
replicacount: 1
deploymentStrategy: null
podAnnotations: {}
resources: {}
podLabels: {}
extraEnv: {}
extraEnvFromSecret: {}
secretKey: null
secretKeyFromExistingSecret:
enabled: false
name: null
key: null
nodeSelector: {}
tolerations: []
affinity: {}
podSecurityContext: {}
defaultPodSecurityContext:
enabled: true
livenessProbe:
path: /health
failureThreshold: 5
initialDelaySeconds: 5 …
```
=> fix: Add missing SSE ingress

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-frontend.yaml, charts/flagsmith/templates/deployment-pgbouncer.yaml, charts/flagsmith/templates/deployment-sse.yaml, charts/flagsmith/templates/deployment-task-processor.yaml, charts/flagsmith/templates/jobs-migrate-analytics-data.yaml, charts/flagsmith/templates/jobs-migrate-db.yaml
release branch
Allow templating in `extraContainers`, closing #304.
Adjust template logic for `extraContainers` to support both string and non-string types. Strings are evaluated as templates, similar to `extraObjects`.
Manually.
```bash
$ helm template flagsmith --dry-run --debug charts/flagsmith/ -f flagsmith.values.yaml
```
```yaml
extraContainers: |
- name: cloud-sql-proxy
image: {{ $.Values.sqlProxySidecar.image.repository }}:{{ $.Values.sqlProxySidecar.image.tag }}
imagePullPolicy: IfNotPresent
command:
- /cloud-sql-proxy
- --structured-logs
```
=> feat: Add templating functionality to extraContainers

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/secrets-pgbouncer.yaml, charts/flagsmith/values.yaml
- [ X ] I have filled in the "Changes" section below?
- [ X ] I have filled in the "How did you test this code" section below?
- [ X ] I have bumped the version number in `/charts/flagsmith/Chart.yaml` in the section `version` or I'm merging to a
release branch
Fixes issues with special characters in database passwords when using pgbouncer. The fix should be backwards compatible as well. Introduces the option to specify 'passwordOverride' needed because of the issue described here : https://github.com/Flagsmith/flagsmith-charts/issues/163
Manually : 
You can go to the chart folder and do : 
1. `helm template flagsmith --set pgbouncer.enabled=true --set databaseExternal.enabled=true --set databaseExternal.host=test --set …
=> Fix pgbouncer password override

.github/workflows/lint-test.yaml, .github/workflows/release.yaml
This is not yet tested.
Makes releasing a manual operation. Remove version bump checks on PRs, and only enforce them on release by running the same lint workflow as part of the release.
=> ci: Use manual releases, check version bump only when releasing

charts/flagsmith/Chart.yaml, charts/flagsmith/values.yaml
release branch
Increases task processor liveness and readiness probe timeout to 30s.
Reviewed the resulting pod specs.
=> fix: Task processor probe timeouts are too optimistic

.github/pull_request_template.md
Not needed anymore after https://github.com/Flagsmith/flagsmith-charts/pull/313 was merged.
=> chore: Remove requirement to bump chart version in PR template

charts/flagsmith/templates/service-sse.yaml
Noticed that the default values.yaml causes a Kubernetes service for SSE to be created, which does nothing. This PR fixes this.
=> fix: Do not deploy SSE k8s service if SSE is disabled

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-task-processor.yaml, charts/flagsmith/templates/service-task-processor.yaml, charts/flagsmith/values.yaml
This PR enables support for new HTTP-based Task Processor liveness and readiness probes.
Ran `helm install` on a local `minikube` cluster, observed new service and expected changes to `task-processor` deployment.
=> feat: Support new Task processor readiness/liveness probes

charts/flagsmith/Chart.yaml, charts/flagsmith/templates/deployment-api.yaml, charts/flagsmith/templates/deployment-task-processor.yaml, charts/flagsmith/values.yaml
This PR adds new values `api.livenessProbe.exec` and `taskProcessor.livenessProbe.exec`. These accept an ExecAction that performs a health check by running a command inside a container: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Probe
This lets customers use TCP healthchecks for the API and task processor, which are not affected by the Gunicorn worker HTTP request queue. For example, this performs a liveness check by using Python to connect to Gunicorn's TCP socket locally:
```yaml
api:
livenessProbe:
exec:
command:
- /usr/bin/python
- -c
- |
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(1)
sock.connect(('localhost', 8000))
sock.close()
```
Tested by using …
=> feat: `exec` liveness probes
