- .github/workflows/lint-test.yaml
Is currently just testing on whatever happens to be KinD's default k8s version.
> Install and test charts in CI using KinD

- charts/flagsmith/Chart.yaml
- charts/flagsmith/README.md
- charts/flagsmith/templates/deployment-api.yaml
- charts/flagsmith/templates/deployment-frontend.yaml
- charts/flagsmith/values.yaml
> More chart docs

- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/service-api.yaml
- charts/flagsmith/templates/service-frontend.yaml
Update the service selectors to accommodate label changes.
> Fix service selectors

- charts/flagsmith/Chart.yaml
- charts/flagsmith/values.yaml
> Reindent values file to use 2 spaces not 4

- charts/flagsmith/Chart.yaml
- charts/flagsmith/README.md
Make the intro to the ingress docs make a bit more sense.
> Tidy ingress docs

- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/ingress-frontend.yaml
Fix for issue:
https://github.com/Flagsmith/flagsmith-charts/issues/30
> Fix incorrect field definition

- .github/workflows/lint-test.yaml
- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/_api_environment.yaml
- Fix secretKeyRef typo
- Bump to chart version 0.2.15
- bump helm/kind-action@v1.2.0
> Fix secretKeyRef typo 

- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/routes-api.yaml
- charts/flagsmith/templates/routes-frontend.yaml
Changed definition of routes so the the host can be defined user or calculated OpenShift. Furthermore, the routes can be enabled separately.
> Changes definition in routes

- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/deployment-api.yaml
- charts/flagsmith/templates/deployment-frontend.yaml
- Fix secretKeyRef typo  (#39)
- Changed path of manage.py file to migration database
- Updated to Flagsmith 2.8
> deployment api

- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/deployment-frontend.yaml
> Allows the frontend to reach the API in clusters which have a custom domain

- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/deployment-pgbouncer.yaml
it should be pgbouncer instead
PS: I didn't update the version in this PR, because there is another one with a new version already
Thanks for submitted a PR! Please check the boxes below:
*Please describe.*  
*Please describe.*
> fix: incorrect property name

- charts/flagsmith/Chart.yaml
- charts/flagsmith/ci/README.md
- charts/flagsmith/ci/test-values.yaml
- charts/flagsmith/templates/tests/test-api-http-health.yaml
- charts/flagsmith/templates/tests/test-api-http-index.yaml
- charts/flagsmith/templates/tests/test-api-http.yaml
- charts/flagsmith/templates/tests/test-frontend-http.yaml
- charts/flagsmith/values.yaml
Add some tests that verify the services are up and accessible. This is progress towards #40.
To test the tests in CI, I pushed the "Force fail to test CI" commit that points curl at the wrong port on the container. This indeed has a :x: so the tests are running in CI and causing a CI fail as they should.
> Simple tests using curl

- charts/flagsmith/templates/deployment-api.yaml
- charts/flagsmith/values.yaml
Update the API readiness check to point correct health endpoint. 
I haven't yet... (hoping that the automated tests will).
> Use health endpoint for checking API health

- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/deployment-api.yaml
- charts/flagsmith/templates/deployment-frontend.yaml
- charts/flagsmith/templates/deployment-pgbouncer.yaml
Fix indentation helper value for `imagePullSecrets`.
Tested on our flagsmith instance with our fork
> fix image pull secrets indentation

- .github/auto_assign.yml
- .github/workflows/auto-assign-pr.yaml
- charts/flagsmith/Chart.yaml
Auto-assigns PRs to the back end team so they don't get missed
> ci: auto assign prs

- .github/workflows/auto-assign-pr.yaml
- charts/flagsmith/Chart.yaml
As per https://github.com/kentaro-m/auto-assign-action/issues/12#issuecomment-1610863459
> ci: fix auto assign permissions

- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/_api_environment.yaml
- charts/flagsmith/templates/_helpers.tpl
- charts/flagsmith/values.yaml
release branch
Adding ability to specify LOG_FORMAT environment variable via Helm values, in relation to issue 166 and associated PR for LOG_FORMAT environment variable to control logging behaviour. Further docs PR to follow. 
Manually;
- Inspected helm template with the value set, and without. Ensured correct linting. 
- Applied template to K8s cluster with empty value set
- Upgraded release with values set to 'json' - verified environment variables set correctly
> Issue 166 json formatted logs charts support

- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/deployment-task-processor.yaml
- charts/flagsmith/values.yaml
> Added extraEnv for taskProcessor service

- .github/workflows/release.yaml
- charts/flagsmith/Chart.yaml
release branch
Add bitnami repo added by [this](https://github.com/Flagsmith/flagsmith-charts/commit/05d899fa45e11801d151ee8900bc0e5b898f4963) commit
n/a
> fix(.github/release): Add bitnami repo

- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/deployment-api.yaml
release branch
_Please describe._
_Please describe._
> fix: Wrong indentaion for allow admin initialization

- charts/flagsmith/Chart.yaml
- charts/flagsmith/templates/NOTES.txt
release branch
We should only show the warning when a secret is not available at all
Manually run the template with and without the change.
> fix: secret warning being shown

- charts/flagsmith/templates/hpa-api.yaml
- charts/flagsmith/values.yaml
Add HPA to support autoscaling api deployment
Tested on local cluster
> feat(hpa): add hpa for api deployment

- charts/flagsmith/values.yaml
_Please describe._
_Please describe._
> feat: test release please

- charts/flagsmith/values.yaml
Do NOT release this until a new release with https://github.com/Flagsmith/flagsmith/pull/5151 and https://github.com/Flagsmith/flagsmith-sse/pull/42 is created.
> feat: Use separate liveness and readiness checks

- charts/flagsmith/templates/configmap-influxdb-setup.yaml
- charts/flagsmith/templates/deployment-api.yaml
- charts/flagsmith/templates/deployment-frontend.yaml
- charts/flagsmith/templates/deployment-pgbouncer.yaml
- charts/flagsmith/templates/deployment-sse.yaml
- charts/flagsmith/templates/deployment-task-processor.yaml
- charts/flagsmith/templates/hpa-api.yaml
- charts/flagsmith/templates/ingress-api.yaml
- charts/flagsmith/templates/ingress-frontend.yaml
- charts/flagsmith/templates/ingress-sse.yaml
- charts/flagsmith/templates/jobs-migrate-analytics-data.yaml
- charts/flagsmith/templates/jobs-migrate-db.yaml
- charts/flagsmith/templates/routes-api.yaml
- charts/flagsmith/templates/routes-frontend.yaml
- charts/flagsmith/templates/secrets-api.yaml
- charts/flagsmith/templates/secrets-influxdb-external.yaml
- charts/flagsmith/templates/secrets-pgbouncer.yaml
- charts/flagsmith/templates/service-api.yaml
- charts/flagsmith/templates/service-frontend.yaml
- charts/flagsmith/templates/service-pgbouncer.yaml
- charts/flagsmith/templates/service-sse.yaml
- charts/flagsmith/templates/service-task-processor.yaml
This ensures that these pods can access secrets in their namespaces by default.
> fix: Add all resources to release namespace
